[options]
admin_passwd = admin
db_user = tracnguyen
addons_path = /Users/tracnguyen/workspace/www/clients/tamara/odoo19/addons,/Users/tracnguyen/workspace/www/clients/tamara/odoo19/odoo/addons,/Users/tracnguyen/workspace/www/clients/tamara/odoo19/custom_addons
http_port = 8069
list_db = True
