[options]
admin_passwd = admin
db_host = localhost
db_port = 5432
db_user = tracnguyen
db_password = False
addons_path = /Users/tracnguyen/workspace/www/clients/tamara/odoo-dev-folk/addons,/Users/tracnguyen/workspace/www/clients/tamara/odoo-dev-folk/odoo/addons,/Users/tracnguyen/workspace/www/clients/tamara/odoo-dev-folk/custom_addons
http_port = 20319
list_db = True
